###
// Login
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "bryant22@gmail.com",
    "password": "bRyant#123"
}

// Profile
###
GET http://localhost:5000/me

// Logout
###
DELETE http://localhost:5000/logout

// Semua Role \\
// Mendapatkan semua data produk
###
GET http://localhost:5000/products

// Mendapatkan semua data kategori
###
GET http://localhost:5000/categories

// User \\
// Register user
###
POST http://localhost:5000/registration
Content-Type: application/json

{
    "firstname": "King",
    "lastname": "Daffa",
    "password": "KingD@ffa123",
    "confPassword": "KingD@ffa123",
    "email": "king@gmail.com",
    "tlp": "0828290978"
}

// Admin \\
// -- Pengaturan user --
// Tambah user baru
###
POST http://localhost:5000/create-user
Content-Type: application/json

{
    "firstname": "Valerie",
    "lastname": "Putra",
    "email": "valerie@gmail.com",
    "tlp": "0823456872"
}

// Menampilkan user berdasarkan id_user
###
GET http://localhost:5000/user/1

// Update data pengguna
###
PATCH http://localhost:5000/editUser/1
Content-Type: application/json

{
    "firstname": "Bryant",
    "lastname": "Sulthan N",
    "password": "bRyant#123",
    "confPassword": "bRyant#123",
    "email": "bryant22@gmail.com",
    "tlp": "082297020445",
    "address": "Bogor",
    "role": "admin"
}

// delete user
###
DELETE http://localhost:5000/removeUser/3

###
// get categories
GET http://localhost:5000/products-category/6

###
//Add to Cart
POST http://localhost:5000/addToCart/3
Content-Type: application/json

###
// cek cart
GET http://localhost:5000/carts
Content-Type: application/json

###
// Update cart qty
PATCH http://localhost:5000/updateCart/33
Content-Type: application/json

{
    "qty": 2
}

###
// Transaction
POST http://localhost:5000/confirm
Content-Type: application/json

{
    "payment": "Bank BRI",
    "acc_num": "4123565",
    "address": "Depok"
}

###
// Transaction List Admin
GET http://localhost:5000/Transactions

###
// confirmation order admin
PATCH http://localhost:5000/confirm/20

###
// cancel order admin
PATCH http://localhost:5000/cancel/1
###
// cancel order user
PATCH http://localhost:5000/cancelOrder/6

###
// shipping order admin
PATCH http://localhost:5000/shipping/20

###
// receive order admin
PATCH http://localhost:5000/receive/6

###
// receive order user
PATCH http://localhost:5000/receiveOrder/6

###
// Wishlist
GET http://localhost:5000/wishlist

###
// add product to wishlist
POST http://localhost:5000/addToWishlist/1

###
// remove product from wishlist
DELETE http://localhost:5000/removeFromWishlist/3

###
// reviews
GET http://localhost:5000/reviews/1