// Create a new user
POST http://localhost:5000/create-users
Content-Type: application/json

{
    "firstname": "Ryo",
    "lastname": "Yamada",
    "username": "yamada",
    "password": "123456",
    "confPassword": "123456",
    "email": "ryo@gmail.com",
    "tlp": "8462587712",
    "role": "user"
}

###
// Register user
POST http://localhost:5000/registration
Content-Type: application/json

{
    "firstname": "Ryan",
    "lastname": "Sulthan",
    "username": "starry05",
    "password": "123456",
    "confPassword": "123456",
    "email": "starry05@gmail.com",
    "tlp": "6290283428"
}

###
// Update user profile
PATCH http://localhost:5000/users/3
Content-Type: application/json

{
    "firstname": "user 2",
    "lastname": "keren",
    "username": "user 2",
    "password": "123456",
    "confPassword": "123456",
    "email": "user2@gmail.com",
    "tlp": "98234235",
    "address": "Bogor",
    "role": "user"
}

###
// get categories
GET http://localhost:5000/products-category/6

###
// Login
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "user2@gmail.com",
    "password": "123456"
}

###
// Logout
DELETE http://localhost:5000/logout

###
//Profile
GET http://localhost:5000/me

###
//Add to Cart
POST http://localhost:5000/addToCart/1
Content-Type: application/json

###
// Update cart qty
PATCH http://localhost:5000/updateCart/33
Content-Type: application/json

{
    "qty": 2
}